### ISSUE TITLE
Implement /member_count command

### ISSUE THREAD

**Issue by tanamaroby** [42-Piscine-Batch-4/discordbot#21]
**Issue Title:**
Implement /member_count Command

**Issue Description:**
As a user of our Discord bot, I want to be able to use a "/member_count" command to retrieve and display the number of members in the server, so that I can quickly get information about the server's size.

**Feature Description:**
- The "/member_count" command should take no arguments.
- When invoked, the bot should retrieve the current number of members in the server where the command was invoked.
- The bot should respond with a message containing the total number of members in the server.

**Acceptance Criteria:**
- The "/member_count" command is successfully implemented and tested.
- Invoking the "/member_count" command should result in the bot retrieving and displaying the total number of members in the server.
- The bot's response should include the total number of members in the server.

**Additional Notes:**
- This feature will provide users with a quick and easy way to access information about the server's membership size.
- Please ensure thorough testing of the "/member_count" command functionality before closing this issue.

**Comment by rbd03** [comment]
does the member count include bots such as DEV_BOT and PROD_BOT?

**Comment by tanamaroby** [comment]
Perchance
